language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
sudo: required


install:
#  - sh install_chrome.sh
  - python setup.py -q install
# command to run tests
script: pytest